USE US_Accidents_DW;
GO

TRUNCATE TABLE [dbo].[FACT_ACCIDENT];
TRUNCATE TABLE [dbo].[DIM_SOURCE];
TRUNCATE TABLE [dbo].[DIM_TIME];
TRUNCATE TABLE [dbo].[DIM_LOCATION];
TRUNCATE TABLE [dbo].[DIM_WEATHER];
TRUNCATE TABLE [dbo].[DIM_ENVIRONMENT];
GO